#!/bin/bash

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color


# Logging functions
log()         { echo -e "${BLUE}-${NC} $*" >&2;    }
log.info()    { echo -e "${BLUE}i $* ${NC}" >&2;   }
log.success() { echo -e "${GREEN}+ $* ${NC}" >&2;  }
log.warn()    { echo -e "${YELLOW}! $* ${NC}" >&2; }
log.error()   { echo -e "${RED}x $* ${NC}" >&2;    }


has-cmd() {
  local cmd_str cmd_bin
  local exit_code=0

  [[ "$#" -eq 0 ]] && {
    log.error "No arguments provided."
    return 2
  }

  for cmd_str in "$@"; do
    cmd_bin="${cmd_str%% *}"

    if ! command -v "$cmd_bin" &>/dev/null; then
      exit_code=1
    fi
  done

  return "$exit_code"
}

clear -x && echo ""

log.info "Adding my-repo repository..."

# Check if running on Arch Linux
if [[ ! -f /etc/arch-release ]]; then
    log.error "This is an Arch Linux repository. Please use an Arch-based system.\n"
    exit 1
fi

# Check for required commands
if ! has-cmd "pacman curl grep sed"; then
    log.error "Missing required commands: pacman, curl, grep, sed\n"
    exit 1
fi

# Check for existing entry
if grep -q "\[my-repo\]" /etc/pacman.conf; then
    log.warn "Repository already exists in pacman.conf"
else
    log.info "Adding repository to pacman.conf..."
    sudo -p "? Enter your password: " bash -c "cat <<'EOF' >> /etc/pacman.conf
[my-repo]
SigLevel = Optional TrustAll
Server = https://mydehq.github.io/my-repo/\$arch
EOF" < /dev/tty
    log.success "Repository added."
fi

echo ""
log.info "Syncing database..."
sudo -p "? Enter your password: " pacman -Sy < /dev/tty

echo ""
log.success "Repository setup complete! Enjoy Our Packages!"
echo ""
